### PR TITLE
Fix DateTimeZone setup: fall back to gmt_offset; php notice fixes

### LINKED ISSUE #5: DateTimeZone Error
I was testing out this plugin for a client and got an error when trying to export.

```
{"success":false,"data":{"message":"DateTimeZone::__construct(): Unknown or bad timezone ()","_ajax_nonce":"6a4ac07ddc"}}
```

I replaced this:

```
/**
 * Builds the file name for the zip
 * Uses the print issue title & day/time
 *
 * @uses get_timezone
 *
 * @return string The zip file name
 */
function get_zip_file_name( ) {
    $date = new \DateTime( 'now', new \DateTimeZone( get_option( 'timezone_string' ) ) );
    return 'Issue ' . $this->issue_title . ' exported on ' . $date->format( 'm-d-y' ) . ' at ' . $date->format( 'h:ia' );
}
```

with your previous version:

```
/**
 * Builds the file name for the zip
 * Uses the print issue title & day/time
 *
 * @uses get_timezone
 *
 * @return string The zip file name
 */
function get_zip_file_name( ) {
    date_default_timezone_set( Core\get_timezone() );
    return sprintf( __( 'Issue %1$s exported on %2$s at %3$s', 'eight-day-week' ), $this->issue_title, date( 'm-d-y' ), date( 'h:ia' ) );
}
```

And the error went away and I could save the Export file. Not sure if you are seeing this on your end, but wanted to let you know.

### PR DESCRIPTION
**Pull request by adamsilverstein**
### Description of the Change

When `timezone_string` is not available (empty), fall back to `gmt_offset` when constructing DateTimeZone for file name.

Also includes some PHP notice fixes and some whitespace changes my editor made (removing stray spacing).

Fixes https://github.com/10up/eight-day-week/issues/5.

### Verification Process

To test this bug, set your WordPress timezone to a "manual" offset instead of a 'named' timezone (under settings->general):

image

Once set, try exporting a print publication. Export will fail and an error will show:

image

After this fix, a zip file will download containing the export.

### Checklist:

- [x] I have read the [**CONTRIBUTING**](https://github.com/10up/eight-day-week/blob/develop/CONTRIBUTING.md) document.
- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [ ] I have added tests to cover my change.
- [x] All new and existing tests passed.

### CODE REVIEW

File: includes/functions/plugins/issue-status.php [hunk 1]
```diff
@@ -94,7 +94,7 @@ function add_issue_status_filters() {
 		echo '<select name="' . esc_attr( $tax_slug ) . '" id="' . esc_attr( $tax_slug ) . '" class="postform">';
 		echo '<option value="">' . sprintf( esc_html_x( 'Show All %s', 'Select option for filtering all issue statuses', 'eight-day-week' ) , esc_html( $tax_name ) ) . '</option>';
 		foreach ( $terms as $term ) {
-			echo '<option value="' . esc_attr( $term->slug ) . '"' . selected( $_GET[ $tax_slug ], $term->slug ) . '>' . esc_html( $term->name ) . '</option>';
+			echo '<option value="' . esc_attr( $term->slug ) . '"' . selected( isset( $_GET[ $tax_slug ] ) && $_GET[ $tax_slug ], $term->slug ) . '>' . esc_html( $term->name ) . '</option>';
```
Comment (helen) [inline includes/functions/plugins/issue-status.php]: This is going to conflict with #28 :)

**Review by helen — APPROVED** [review]
